### ISSUE TITLE
Thanks! This Just Helped Me Out! 😀

### ISSUE THREAD

**Issue by zicklag** [nyantec/iptool#6]
Hey there! Just wanted to shout out a quick thanks for this crate. I'm trying to build an ultra-minimal and secure operating system for running servers and I needed a way to run `ip link set up` without having the `ip` utility available. This worked so far, so thanks!

**Comment by zicklag** [comment]
I'll go ahead and close this because it's not actually an issue. :wink:

**Comment by Kloenk** [comment]
Your welcome. I'm currently working on creating interfaces (dummy/veth). So maybe someday we have time to create a complete replacement for ip :)
